=head1 Nagios and Icinga plugins



=head2 check_domain

The plugin checks domain expiration date and alerts if:

=over

=item *

domain is expired

=item *

domain will expire in B<warnings> days (WARNING)

=item *

domain will expire in B<critical> days (CRITICAL)

=back


=head2 check_avisosms_balance

The plugin checks SMS balance on L<avisosms.ru> service.

=head2 avisosms

The script sends SMS through L<avisosms.ru> service.

=cut
